connect:
  host: 127.0.0.1
  port: 5672

exchange:
  trade:
    name: exchange.trade
    type: headers
  notification:
    name: exchange.notification
    type: direct
  orderbook:
    name: exchange.orderbook
    type: fanout
  binance:
    name: exchange.binance
  lending:
    name: exchange.lending
    type: headers
  loanbook:
    name: exchange.loanbook
    type: fanout

queue:
  matching:
    name: exchange.matching
    durable: true
  slave_book:
    name: exchange.orderbook.slave
    durable: true
  new_trade:
    name: exchange.trade.new
    durable: true
  order_processor:
    name: exchange.order.processor
    durable: true
  market_ticker:
    name: exchange.trade.market_ticker
  pusher_market:
    name: exchange.pusher.market
  pusher_member:
    name: exchange.pusher.member
  withdraw_coin:
    name: exchange.withdraw.coin
  deposit_coin:
    name: exchange.deposit.coin
  deposit_coin_address:
    name: exchange.deposit.coin.address
    durable: true
  email:
    name: exchange.notification.email
    durable: true
  sms:
    name: exchange.notification.sms
    durable: true
  loan_matching:
    name: exchange.loan_matching
    durable: true
  slave_loan_book:
    name: exchange.loanbook.slave
    durable: true
  new_lending:
    name: exchange.lending.new
    durable: true
  loan_processor:
    name: exchange.loan.processor
    durable: true
  pusher_loan_market:
    name: exchange.pusher.loan_market
  binance_processor:
    name: exchange.binance.processor
    durable: true

binding:
  matching:
    queue: matching
    clean_start: true
  slave_book:
    queue: slave_book
    exchange: orderbook
  trade_executor:
    queue: new_trade
    manual_ack: true
  order_processor:
    queue: order_processor
    manual_ack: true
  market_ticker:
    queue: market_ticker
    exchange: trade
  pusher_market:
    queue: pusher_market
    exchange: trade
  pusher_member:
    queue: pusher_member
  withdraw_coin:
    queue: withdraw_coin
  deposit_coin:
    queue: deposit_coin
  deposit_coin_address:
    queue: deposit_coin_address
  email_notification:
    queue: email
    exchange: notification
  sms_notification:
    queue: sms
    exchange: notification
  loan_matching:
    queue: loan_matching
    clean_start: true
  slave_loan_book:
    queue: slave_loan_book
    exchange: loanbook
  lending_executor:
    queue: new_lending
    manual_ack: true
  loan_processor:
    queue: loan_processor
    manual_ack: true
  pusher_loan_market:
    queue: pusher_loan_market
    exchange: lending
  binance_processor:
    queue: binance_processor
    exchange: binance

channel:
  trade_executor:
    prefetch: 5
  order_processor:
    prefetch: 5
  lending_executor:
    prefetch: 5
  loan_processor:
    prefetch: 5
