defaults: &defaults

  # sites hosts
  # session expire seconds
  # admin role account
  URL_HOST: crypto.365-exchange.com:3000
  URL_UI: crypto.365-exchange.com
  URL_SCHEMA: https
  SESSION_EXPIRE: '60'
  ADMIN: 'admin@crypto.365-exchange.com'
  TIMEZONE: 'UTC'

  REDIS_URL: redis://127.0.0.1:6379

  # below settings only in production env
  # system notify mail settings
  # --------------------------------------------------------------
  SMTP_PORT: '587'
  SMTP_DOMAIN: crypto-smtp@365-exchange.com
  SMTP_ADDRESS: mail.365-exchange.com
  SMTP_USERNAME: crypto-smtp@365-exchange.com
  SMTP_PASSWORD: bHF34#55jgExDpt
  SMTP_AUTHENTICATION: plain # could be plain, login or cram_md5

  SUPPORT_MAIL: support@crypto.365-exchange.com
  SYSTEM_MAIL_FROM: system@crypto.365-exchange.com
  SYSTEM_MAIL_TO: group@crypto.365-exchange.com
  OPERATE_MAIL_TO: support@crypto.365-exchange.com

  # WebSocket Streaming API settings
  # --------------------------------------------------------------
  WEBSOCKET_HOST: 0.0.0.0
  WEBSOCKET_PORT: '8080'
  # Uncomment below to enable secure WebSocket (wss)
  #WEBSOCKET_SSL_KEY: 'your_server.key'
  #WEBSOCKET_SSL_CERT: 'your_server.crt'

  # twilio setting
  # --------------------------------------------------------------
  # https://github.com/twilio/twilio-ruby
  #
  TWILIO_NUMBER: YOUR_TWILIO_NUMBER
  TWILIO_SID: YOUR_TWILIO_SID
  TWILIO_TOKEN: YOUR_TWILIO_TOKEN

  # Binance setting
  # --------------------------------------------------------------
  # https://github.com/twilio/twilio-ruby
  #
  BINANCE_API_KEY: 'LIrVAqK27BDrgZQ30MhKcH6f4RiJ5U2Q1krravy4aDT7lHqFwor7tgMh5UsgQ70U'
  BINANCE_SEC_KEY: 'NzXrJn4xa3JzfAnGy8JUCDXNe4lOsNFQxI9aTHA01fuliUfspuy2PnHgFFTvXRnE'

  # margin trading and loan setting
  # --------------------------------------------------------------
  #
  LOAN_MAX_RATE: '100'
  MARGIN_MAINTENANCE: '20'

  # referral settings
  # --------------------------------------------------------------
  #
  REFERRAL_RATE_STEP: '0.0001'
  REFERRAL_MAX_TIER: '10'

development:
  <<: *defaults
  # sites hosts
  URL_HOST: localhost:4000
  URL_UI: localhost:3000
  URL_SCHEMA: http

test:
  <<: *defaults

production:
  <<: *defaults
