defaults: &defaults

  # sites hosts
  # session expire seconds
  # admin role account
  URL_HOST: rabbit-cc.com
  URL_SCHEMA: https
  SESSION_EXPIRE: '60'
  ADMIN: 'admin@rabbit-cc.com'
  TIMEZONE: 'UTC'

  REDIS_URL: redis://127.0.0.1:6379

  # below settings only in production env
  # system notify mail settings
  # --------------------------------------------------------------
  SMTP_PORT: '587'
  SMTP_DOMAIN: rabbit-cc.com
  SMTP_ADDRESS: mail.smtp2go.com
  SMTP_USERNAME: exchange-coin@hs-sup.com
  SMTP_PASSWORD: 3ysze8Vf95sV
  SMTP_AUTHENTICATION: plain # could be plain, login or cram_md5

  SUPPORT_MAIL: support@rabbit-cc.com
  SYSTEM_MAIL_FROM: system@rabbit-cc.com
  SYSTEM_MAIL_TO: group@rabbit-cc.com
  OPERATE_MAIL_TO: support@rabbit-cc.com

  # WebSocket Streaming API settings
  # --------------------------------------------------------------
  WEBSOCKET_HOST: 0.0.0.0
  WEBSOCKET_PORT: '8080'
  # Uncomment below to enable secure WebSocket (wss)
  #WEBSOCKET_SSL_KEY: 'your_server.key'
  #WEBSOCKET_SSL_CERT: 'your_server.crt'

  # pusher settings
  # --------------------------------------------------------------
  # dependence Pusher (http://pusher.com) service
  # you can change your key for production environment.
  # we support development key and secret
  # uncomment below line only development or test
  #

  PUSHER_APP: '416932'
  PUSHER_KEY: 7af1ba12c685b6f366f2
  PUSHER_SECRET: 03e878db6d77ed06705f

  PUSHER_HOST: api-us2.pusher.com
  # Careful in Host - pusher zone binding
  PUSHER_PORT: '80'
  PUSHER_WS_PORT: '80'
  PUSHER_WSS_PORT: '443'
  PUSHER_ENCRYPTED: true

  # twilio setting
  # --------------------------------------------------------------
  # https://github.com/twilio/twilio-ruby
  #
  TWILIO_NUMBER: YOUR_TWILIO_NUMBER
  TWILIO_SID: YOUR_TWILIO_SID
  TWILIO_TOKEN: YOUR_TWILIO_TOKEN

  # margin trading and loan setting
  # --------------------------------------------------------------
  #
  LOAN_MAX_RATE: '100'


development:
  <<: *defaults
  # sites hosts
  URL_HOST: 127.0.0.1:3000
  URL_SCHEMA: http

test:
  <<: *defaults

production:
  <<: *defaults
