- id: 2
  key: satoshi
  code: btc
  symbol: "฿"
  type: coin
  precision: 8
  base_factor: 100_000_000
  quick_withdraw_max: 0
  api_client: BTC
  rpc: http://rpcuser:rpcpass@127.0.0.1:18332
  blockchain: https://blockchain.com/tx/#{txid}
  address_url: https://blockchain.com/address/#{address}
  case_sensitive: true

- id: 3
  key: ethereum
  code: eth
  symbol: "Ξ"
  type: coin
  precision: 8
  base_factor: 1_000_000_000_000_000_000
  quick_withdraw_max: 0
  api_client: ETH
  rpc: http://127.0.0.1:8545
  blockchain: https://etherscan.io/tx/#{txid}
  address_url: https://etherscan.io/address/#{address}
  case_sensitive: false

- id: 4
  key: litecoin
  code: ltc
  symbol: "Ł"
  type: coin
  precision: 8
  base_factor: 100_000_000
  quick_withdraw_max: 0
  api_client: BTC
  rpc: http://repxcuser:repxcpass@127.0.0.1:18332
  blockchain: http://explorer.litecoin.net/tx/#{txid}
  address_url: http://explorer.litecoin.net/address/#{address}
  case_sensitive: true

- id: 5
  key: sakurabloom
  code: skb
  symbol: "SKB"
  type: coin
  precision: 8
  base_factor: 100_000_000
  quick_withdraw_max: 0
  erc20_contract_address: '0x4af328c52921706dcb739f25786210499169afe6'
  api_client: ERC20
  rpc: http://127.0.0.1:8545
  blockchain: https://etherscan.io/tx/#{txid}
  address_url: https://etherscan.io/token/0x4af328c52921706dcb739f25786210499169afe6?a={address}
  case_sensitive: false

- id: 6
  key: masoyamacoin
  code: mas
  symbol: "MAS"
  type: coin
  precision: 8
  base_factor: 100_000_000
  quick_withdraw_max: 0
  erc20_contract_address: '0xf355164187e533b1969b4de46737c4e8bc9ae7e2'
  api_client: ERC20
  rpc: http://127.0.0.1:8545
  blockchain: https://etherscan.io/tx/#{txid}
  address_url: https://etherscan.io/token/0xf355164187e533b1969b4de46737c4e8bc9ae7e2?a={address}
  case_sensitive: false