development: &defaults
  adapter: mysql2
  encoding: utf8
  database: ngo_development
  username: root
  password: admin
  pool: 10
  reconnect: true

test:
  <<: *defaults
  database: ngo_test

production:
  <<: *defaults
  database: ngo_production
