development: &defaults
  adapter: mysql2
  encoding: utf8
  database: rabbit-cc_development
  username: root
  password: admin
  pool: 10
  reconnect: true

test:
  <<: *defaults
  database: rabbit-cc_test

production:
  <<: *defaults
  database: rabbit-cc_production
