development: &defaults
  adapter: mysql2
  encoding: utf8
  database: m365_development
  username: root
  password: admin
  pool: 10
  reconnect: true

test:
  <<: *defaults
  database: m365_test

production:
  <<: *defaults
  database: m365_production
