- id: 200
  key: satoshi
  currency: btc
  min_confirm: 1
  max_confirm: 3
  min_amount: 0.0050
  inuse: true
  fixed: 8
  fee: 0.0010
  type: WithdrawChannelSatoshi

- id: 300
  key: ethereum
  currency: eth
  min_confirm: 1
  max_confirm: 3
  min_amount: 0.0050
  inuse: true
  fixed: 8
  fee: 0.0010
  type: WithdrawChannelEthereum

- id: 400
  key: litecoin
  currency: ltc
  min_confirm: 1
  max_confirm: 3
  min_amount: 0.0050
  inuse: true
  fixed: 8
  fee: 0.0010
  type: WithdrawChannelLitecoin

- id: 500
  key: sakurabloom
  currency: skb
  min_confirm: 1
  max_confirm: 3
  min_amount: 0.0050
  inuse: true
  fixed: 8
  fee: 0.0010
  type: WithdrawChannelSakurabloom

- id: 600
  key: masoyamacoin
  currency: mas
  min_confirm: 1
  max_confirm: 3
  min_amount: 0.0050
  inuse: true
  fixed: 8
  fee: 0.0010
  type: WithdrawChannelMasoyamacoin
